
name: secrets
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        env: 
          REACT_APP_MAPTOKEN: ${{ secrets.REACT_APP_MAPTOKEN }}
          REACT_APP_BASEURL: ${{ secrets.REACT_APP_BASEURL }}